### ISSUE TITLE
.ignore file

### ISSUE THREAD

**Issue by sencerburak** [jahwag/ClaudeSync#20]
Is your feature request related to a problem? Please describe.

We need a .ignore file to be able to ignore certain files and structures. I just had entire node modules directory synced :D

Lack of option to ignore or include certain paths and files

Describe the solution you'd like

A .ignore implementation

A .ignore file that can be configured

Describe alternatives you've considered
Use case
Describe how you would use this feature and how it would benefit your workflow with ClaudeSync.
Additional context
Add any other context, screenshots, or examples about the feature request here.
Environment (if relevant):

OS: [e.g. Windows 10, macOS 11.4, Ubuntu 20.04]

MacOS

Python version: [e.g. 3.8.10]
ClaudeSync version: [e.g. 0.3.7]

Are you willing to contribute to this feature?

Yes

Let us know if you're interested in helping implement this feature or if you're just suggesting an idea.

I can help.

**Comment by jahwag** [comment]
The functionality you’re referring to is covered in our README, where it states that .gitignore is parsed by ClaudeSync. Please review the documentation, and if you still experience issues after that, let us know with more details.
