### ISSUE TITLE
Configuration option to disable chat sync

### ISSUE THREAD

**Issue by TfTHacker** [jahwag/ClaudeSync#31]
Great tool. Many thanks for your great work.

I am interested in syncing just a folder up to a project. It would be nice to disable the "chat" sync.

I would imagine this as a setting in configuration or at the project level.

**Comment by TfTHacker** [comment]
Thank you for adding this feature. it works great.

**Comment by ChrisTorng** [comment]
I can't find anything about the config to disable chat sync. The `claudesync chat` isn't listed in [Quick reference](https://github.com/jahwag/ClaudeSync/wiki/quick-reference), and `claudesync config ls` has not chat related item.

**Comment by TfTHacker** [comment]
It isn't obvious, but this worked for me `claudesync project sync`.
