### ISSUE TITLE
Current implementation may violate Anthropic's Terms of Service and Usage Policy. Ban risk?

### ISSUE THREAD

**Issue by rmcc3** [jahwag/ClaudeSync#38]
**Details:**
1. Automated Access:
   TOS states: 
   > "Except when you are accessing our Services via an Anthropic API Key or where we otherwise explicitly permit it, to access the Services through automated or non-human means, whether through a bot, script, or otherwise."
   
   Current implementation uses a session key, not an API key. Unclear if this is permitted.

2. Account Security:
   TOS states:
   > "You may not share your Account login information, Anthropic API key, or Account credentials with anyone else. You also may not make your Account available to anyone else."
   
   Using a session key might be interpreted as sharing access, even if it is running locally.

3. Platform Usage:
   Usage Policy prohibits:
   > "Intentionally bypass capabilities or restrictions established within our products for the purposes of instructing the model to produce harmful outputs"
   
   Automated access could potentially be seen as bypassing normal usage restrictions.

**Suggested actions:**
1. Reach out to Anthropic support for clarification on automated access using session keys
2. Add clear warnings in README and script about potential TOS violations

**Comment by jahwag** [comment]
Opened discussion at https://discord.com/channels/1072196207201501266/1270344413671067774/1270344413671067774

**Comment by rmcc3** [comment]
Looks like that was deleted?

**Comment by jahwag** [comment]
> Looks like that was deleted?

What was?
