### ISSUE TITLE
Support for Team plan

### ISSUE THREAD

**Issue by quinn** [jahwag/ClaudeSync#43]
Hi, after I enter the expiry time, I get prompted to enter the sessionKey again, which then prompts for the expires time, which then prompts for the sessionKey, etc. in a loop. 

```
claudesync api login claude.ai
To obtain your session key, please follow these steps:
1. Open your web browser and go to https://claude.ai
2. Log in to your Claude account if you haven't already
3. Once logged in, open your browser's developer tools:
   - Chrome/Edge: Press F12 or Ctrl+Shift+I (Cmd+Option+I on Mac)
   - Firefox: Press F12 or Ctrl+Shift+I (Cmd+Option+I on Mac)
   - Safari: Enable developer tools in Preferences > Advanced, then press Cmd+Option+I
4. In the developer tools, go to the 'Application' tab (Chrome/Edge) or 'Storage' tab (Firefox)
5. In the left sidebar, expand 'Cookies' and select 'https://claude.ai'
6. Locate the cookie named 'sessionKey' and copy its value. Ensure that the value is not URL-encoded.
Please enter your sessionKey: XXXXX
Please enter the expires time for the sessionKey [Sat, 07 Sep 2024 18:46:52 UTC]: 
Please enter your sessionKey: XXXXX
Please enter the expires time for the sessionKey [Sat, 07 Sep 2024 18:46:55 UTC]: 
Please enter your sessionKey: XXXXX
Please enter the expires time for the sessionKey [Sat, 07 Sep 2024 18:47:11 UTC]: 
Please enter your sessionKey: 
```

**Comment by quinn** [comment]
OK I dug in on the code a little bit. It looks like my organizations array is empty, and an empty array is falsy in python. Not sure why it is empty though.

**Comment by jahwag** [comment]
Yes, that was added to the login flow fairly recently, but it seems the handling of the unhappy path could use some improvement.

Could you check if your https://claude.ai/api/organizations endpoint includes something like this (with capabilities: chat & claude_pro)?"

```
 {
        "uuid": "e731f9fc-edb4-420d-aa35-952e2ce77137",
        "name": "Organization 1",
        "settings": {
            "claude_console_privacy": "default_private",
            "allowed_invite_domains": null
        },
        "capabilities": [
            "chat",
            "claude_pro"
        ],
        "rate_limit_tier": "default_claude_ai",
        "billing_type": "stripe_subscription",
        "free_credits_status": "available",
        "data_retention": "default",
        "api_disabled_reason": null,
        "api_disabled_until": null,
        "billable_usage_paused_until": null,
        "raven_type": null,
        "created_at": "2024-07-10T20:04:41.970943Z",
        "updated_at": "2024-07-15T16:47:58.586794Z",
        "active_flags": []
    },
```

**Comment by quinn** [comment]
none have "claude_pro". I have "chat", "raven", and "api" spread across six orgs all with the same name

**Comment by jahwag** [comment]
Do you have a Personal Professional Plan or just Free Chat + (Paid) API?

**Comment by quinn** [comment]
i have a pro Team plan thru my org, could that be the problem?

**Comment by jahwag** [comment]
Yes, that’s the issue. Unfortunately, I don’t have access to the Team plan, and unless someone with that plan contributes, this limitation will persist. You could try manually setting the organization in ~/.claudesync/config.json, but I’m unable to provide support for that approach.

**Comment by quinn** [comment]
Happy to take a look and try to open a PR, any advice on where I should start?

**Comment by quinn** [comment]
I'll try hardcoding the org ID and i'll let you know if i get stuck.

**Comment by jahwag** [comment]
> Happy to take a look and try to open a PR, any advice on where I should start?

If you find that any particular org of yours works, you'll need to modify the capabilities filter in claudesync.providers.base_claude_ai.BaseClaudeAIProvider.get_organizations to have it shown as an option for selection.


> I'll try hardcoding the org ID and i'll let you know if i get stuck.

Best of luck!

**Comment by quinn** [comment]
@jahwag I have a PR that seems to grab the org that works for me. It is called "raven", i guess?
