### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by CharlesFr** [jahwag/ClaudeSync#47]
When trying to login I get this error, the timestamp is directly copied from the `Expires / Max-age` column in Chrome inspect.
```
Please enter the expires time for the sessionKey [Mon, 09 Sep 2024 19:39:46 UTC]: 2024-09-09T19:33:06.168Z
The entered date does not match the required format. Please try again.
```

I'm on Ubuntu

**Comment by jahwag** [comment]
The required format is right there: **Mon, 09 Sep 2024 19:39:46 UTC**]. They string you entered does not match it, as indicated by the error.
