### ISSUE TITLE
Error: No active provider set. Please select a provider for this project.

### ISSUE THREAD

**Issue by raine** [jahwag/ClaudeSync#61]
Hello,

Struggling to get the latest (0.5.6) version to sync.

```
~/c/myproject % claudesync project create
Enter a title for your new project [myproject]:
Enter the project description [Project created with ClaudeSync]:
Enter the absolute path to your local project directory [/Users/raine/code/myproject]:
Pick the provider to use for this project (claude.ai) [claude.ai]:
Project 'myproject' (uuid: xxx) has been created successfully.

Project setup complete. You can now start syncing files with this project. URL: https://claude.ai/project/xxx
~/c/myproject % claudesync push
Error: No active provider set. Please select a provider for this project.
```

Not sure why it complains about provider not being set when the `claudesync project create` command set the provider presumably.

Any ideas? Thanks.

Btw, README appears outdated. References the command `claudesync project sync` which no longer exists.

**Comment by jahwag** [comment]
Please create a [bug report](https://github.com/jahwag/ClaudeSync/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=) and fill out the _entire_ form.

**Comment by adar2378** [comment]
same issue in the latest version of claudesync. It just appears when we are trying to sync a files for a project. I ran `claudesync push` after selecting organization and project.

@jahwag Maybe the docs are outdated, could you please check if you have time? We will fill out a proper bug report later.
