### ISSUE TITLE
Getting an error when I enter my sessonkey from Chrome tab

### ISSUE THREAD

**Issue by niiraav** [jahwag/ClaudeSync#64]
**Describe the bug**

**To Reproduce**
1. Go to 'Cursor'
2. Run command 'laudesync auth login'
3. See the below error when I enter my session key:
2024-09-09 13:59:37,106 - ERROR - URL Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
API request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
Failed to retrieve organizations. Please enter a valid sessionKey.
Please enter your sessionKey: 

**Expected behavior**
Get authenticated
**Error messages**
If applicable, provide the full error message or stack trace.
2024-09-09 12:30:49,328 - ERROR - URL Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
API request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
Failed to retrieve organizations. Please enter a valid sessionKey.

**Environment (please complete the following information):**
 - OS: [macOS latest]

```
claudesync config set log_level DEBUG
```
<img width="883" alt="image" src="https://github.com/user-attachments/assets/e065ae22-3f8e-4a33-860a-1ec94b4a43ed">

**Comment by beeekind** [comment]
I'm seeing this same issue on the same platform in versions 0.6.1, 0.6.0, and 0.5.7. Is this a user error and if so what steps can I take to fix the problem locally? Thank you.
