### ISSUE TITLE
Can't paste session key

### ISSUE THREAD

**Issue by ParisMolver** [jahwag/ClaudeSync#78]
### Operating System

Windows 11

### Python Version

3.12

### ClaudeSync Version

0.6.0

### Installation Type

New

### Configuration

.

### Steps to Reproduce

Maybe your cmd prompt works different

### Description

I just installed, went to go authenticate and when I copied my key I found I couldn't paste it.

I then thought "maybe i can type claudesync auth logic {key}" and it's not a valid argument.

Do people manually type in the 50 or so characters? how long does a key last?

**Comment by ParisMolver** [comment]
I was so grumpy about having to punch in all those letters just to use the project that I got the code I needed to do it for me

`import time
import pyautogui

def delayed_typing(text, delay=0.05):
    # Wait for 5 seconds before starting
    
    # Type the text character by character
    for char in text:
        pyautogui.write(char)
        # print(char, end='')
        time.sleep(delay)

# Example usage
text_to_type = "sk-TMiuVgAA"
for i in range(5, 0, -1):
    print(i)
    time.sleep(1)
delayed_typing(text_to_type)
print('done')`

**Comment by jahwag** [comment]
Did you try pressing Ctrl+V then Enter?

**Comment by ParisMolver** [comment]
Hi there, I will try this. It possibly worked but without the console feedback I thought it was broken. Is it possible for secure input to show **** instead of nothing?
