### ISSUE TITLE
sometimes it misses files

### ISSUE THREAD

**Issue by sirus20x6** [jahwag/ClaudeSync#80]
### Operating System

Arch Linux

### Python Version

Python 3.12.6

### ClaudeSync Version

0.6.1

### Installation Type

New

### Configuration

...

### Steps to Reproduce

claudesync push

### Description

sometimes when I push and there are a lot of small files the web interface shows that some of the files didn't in fact sync. seems kinda random

**Comment by jahwag** [comment]
@sirus20x6  Thank you for filing this issue. Without logs, it's difficult to say what this could be. As a work-around, please try using the single-file mode and create a new project to have a clean remote workspace:
`claudesync config set compression_algorithm pack`

**Comment by sirus20x6** [comment]
I'll see if I can add logs soon. I was in a hurry earlier
