### ISSUE TITLE
 Issue with the request to https://api.claude.ai/api/organizations

### ISSUE THREAD

**Issue by WalidFerjani2** [jahwag/ClaudeSync#91]
### Operating System

Linux

### Python Version

Python 3.8.10

### ClaudeSync Version

0.5.7

### Installation Type

New

### Configuration

{
  "active_organization_id": null,
  "active_project_id": null,
  "active_project_name": null,
  "active_provider": null,
  "claude_api_url": "https://api.claude.ai/api",
  "compression_algorithm": "none",
  "curl_use_file_input": false,
  "file_categories": {
    "all_files": {
      "description": "All files not ignored",
      "patterns": [
        "*"
      ]
    },
    "all_source_code": {
      "description": "All source code files",
      "patterns": [
        "*.java",
        "*.py",
        "*.js",
        "*.ts",
        "*.c",
        "*.cpp",
        "*.h",
        "*.hpp",
        "*.go",
        "*.rs"
      ]
    },
    "build_config": {
      "description": "Build configuration files",
      "patterns": [
        "pom.xml",
        "build.gradle",
        "package.json",
        "setup.py",
        "Cargo.toml",
        "go.mod"
      ]
    },
    "production_code": {
      "description": "Production source code",
      "patterns": [
        "src/**/*.java",
        "src/**/*.py",
        "src/**/*.js",
        "src/**/*.ts"
      ]
    },
    "test_code": {
      "description": "Test source code",
      "patterns": [
        "test/**/*.java",
        "tests/**/*.py",
        "**/test_*.py",
        "**/*Test.java"
      ]
    }
  },
  "local_path": null,
  "log_level": "DEBUG",
  "max_file_size": 32768,
  "prune_remote_files": false,
  "session_key": null,
  "session_key_expiry": null,
  "submodule_detect_filenames": [
    "pom.xml",
    "build.gradle",
    "package.json",
    "setup.py",
    "Cargo.toml",
    "go.mod"
  ],
  "two_way_sync": false,
  "upload_delay": 0.5
}

### Steps to Reproduce

claudesync auth login
Choose provider (claude.ai) [claude.ai]: claude.ai
A session key is required to call: https://api.claude.ai/api
To obtain your session key, please follow these steps:
1. Open your web browser and go to https://claude.ai
2. Log in to your Claude account if you haven't already
3. Once logged in, open your browser's developer tools:
   - Chrome/Edge: Press F12 or Ctrl+Shift+I (Cmd+Option+I on Mac)
   - Firefox: Press F12 or Ctrl+Shift+I (Cmd+Option+I on Mac)
   - Safari: Enable developer tools in Preferences > Advanced, then press Cmd+Option+I
4. In the developer tools, go to the 'Application' tab (Chrome/Edge) or 'Storage' tab (Firefox)
5. In the left sidebar, expand 'Cookies' and select 'https://claude.ai'
6. Locate the cookie named 'sessionKey' and copy its value. Ensure that the value is not URL-encoded.
Please enter your sessionKey:
Please enter the expires time for the sessionKey (optional) [Thu, 19 Dec 2024 10:48:08 UTC]:
2024-11-19 10:48:09,075 - DEBUG - Making GET request to https://api.claude.ai/api/organizations
2024-11-19 10:48:09,075 - DEBUG - Headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0', 'Content-Type': 'application/json', 'Accept-Encoding': 'gzip'}
2024-11-19 10:48:09,075 - DEBUG - Cookies: {'sessionKey': 'MY_SESSION_ID'}
2024-11-19 10:48:09,127 - DEBUG - Request failed: HTTP Error 403: Forbidden
2024-11-19 10:48:09,127 - DEBUG - Response status code: 403
2024-11-19 10:48:09,131 - DEBUG - Response headers: Date: Tue, 19 Nov 2024 10:48:09 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Set-Cookie: __cf_bm=hghzICK2tZm.8XQJbm9_bUWcAQhfC.rRHXjbOgZ7L8I-1732013289-1.0.1.1-ChnK3HvMgG5Le5Lrskz_3LY3ZPIObC6v0RWScg_xhq25hca.gyyLPJRQvXvH4ftB383rp9bw2og.UKqyjSoKMg; path=/; expires=Tue, 19-Nov-24 11:18:09 GMT; domain=.claude.ai; HttpOnly; Secure; SameSite=None
Vary: Accept-Encoding
X-Robots-Tag: none
Server: cloudflare
CF-RAY: 8e4fa050fba3eba9-CDG
Content-Encoding: gzip
alt-svc: h3=":443"; ma=86400

2024-11-19 10:48:09,132 - DEBUG - Response content: {"error":{"message":"We are unable to serve your request","type":"permission_error"}}
Received a 403 Forbidden error.

### Description

I encountered a 403 Forbidden error when trying to authenticate and make a GET request to https://api.claude.ai/api/organizations. I followed the authentication steps to obtain the session key, but the request still fails with a 403 status. The response indicates a "permission_error" message.

**Comment by jahwag** [comment]
Regrettably, I’m unable to assist individual users in diagnosing the cause of a 403 error from Cloudflare.
